### ISSUE TITLE
Feature request - Ability to use externally created/update substvar file during deployment

### ISSUE THREAD

**Issue by rishikeshpalve** [TIBCOSoftware/bwce-docker#11]
As DevOps user, I'd like to have an ability to create a completely new substvar file or update existing substvar file without getting into Studio and use that file while creating BWCE application docker image. This feature would be very useful as it will remove need to go back to Studio to create a new profile for new environment or update existing file to cater to configuration changes.

**Comment by krsharma19** [comment]
This feature is already present in docker. Just place the new substvar file (i.e. custom.substvar) along with the docker repo cloned from https://github.com/TIBCOSoftware/bwce-docker and while doing docker run, pass BW_PROFILE="custom.substvar". This will enable the user to create a completely new substvar file without getting into the studio.

**Comment by awagle** [comment]
Closing issue based on comment from @krsharma19
