### ISSUE TITLE
How to run bwce application having database pallets in Docker 

### ISSUE THREAD

**Issue by smwatage** [TIBCOSoftware/bwce-docker#16]

**Comment by smwatage** [comment]
I have created a base image as shown in documents. And created a flow with jdbc SQL direct . Connecting to MySQL container details . Running bwce application in one container and MySQL in another container . Application trying to connect MySQL container for db.

Wen I deploy an application , it is deploying successful. But wen I hit service jdbc connection issue with property conf .

Can someone help !?

**Comment by awagle** [comment]
Please check the hostname used. If you mysql running in another container you need to setup docker networking to get one container talk to another. An easier way would be to have the containers startup as a docker-compose script and use the service name of the MySQL container in the hostname of the JDBC URL.
